Repository dev-White-team/WhiteBot, pull requests merged in 2022-07, with the labels that each got.

#60 고급 계산기
  functions/advanced_caculator.py
Labels: new feature

#67 번역 기능 언어 추가
  functions/translate.py
Labels: enhancement

#69 오류문구 수정
  functions/white_currency.py
  requirements.txt
Labels: enhancement, typo

#71 환율 기능 코드 리팩토링
  functions/currency.py
  utils/database.py
Labels: enhancement

#70 코로나 기능 추가
  functions/covid.py
  requirements.txt
Labels: new feature

#72 맞춤법 검사 기능 추가
  functions/spellcheck.py
  utils/hanspell/__init__.py
  utils/hanspell/constants.py
  utils/hanspell/response.py
  utils/hanspell/spell_checker.py
Labels: new feature

#73 환율 기능의 오타
  functions/currency.py
Labels: bug
