Repository dev-White-team/WhiteBot, pull requests merged in 2022-03, with the labels that each got.

#42 계산 기능 추가
  functions/calc.py
  functions/manage.py
  main.py
Labels: enhancement

#48 명령어 한국어로 전체 번역
  README.md
  functions/calc.py
  functions/code.py
  functions/etc.py
  functions/help.py
  functions/manage.py
  functions/playing.py
  functions/translate.py
  functions/vote.py
  functions/weather.py
  functions/youtube.py
Labels: enhancement

#50 해독 기능의 오타
  functions/code.py
Labels: typo

#53 알수없는 오류로 인한 임시삭제
  functions/weather.py
Labels: bug
