Repository dev-White-team/WhiteBot, pull requests merged in 2022-08, with the labels that each got.

#75 URL Shortener 기능 추가
  functions/urlshortener.py
Labels: new feature

#76 flake8 ignore 추가
  .flake8
Labels: invalid

#77 WhiteBot 코드 클래스로 변경
  main.py
  utils/whitebot.py
Labels: enhancement

#78 에러 핸들링 기능 추가
  utils/whitebot.py
Labels: new feature

#79 코드 개선 작업
  .gitignore
  functions/calc.py
  functions/code.py
  functions/currency.py
  functions/etc.py
  functions/help.py
  functions/manage.py
  functions/playing.py
  functions/weather.py
  utils/database.py
  utils/logging.py
Labels: enhancement

#86 환경변수 예시 파일 추가
  .env.example
  CONTRIBUTING.md
Labels: enhancement
